// Global
export const NO_OP = 'NO_OP';

// Login
export const AUTH = 'AUTH';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';

// Search
export const LOAD_AIRPORTS = 'LOAD_AIRPORTS';
export const LOAD_TERMINALS = 'LOAD_TERMINALS';
export const LOAD_GATES = 'LOAD_GATES';
export const SELECT_AIRPORT = 'SELECT_AIRPORT';
export const SELECT_TERMINAL = 'SELECT_TERMINAL';
export const SELECT_GATE = 'SELECT_GATE';

// Results
export const LOAD_RESTAURANTS = 'LOAD_RESTAURANTS';
export const SELECT_RESTAURANT = 'SELECT_RESTAURANT';

// Menu
export const LOAD_MENU = 'LOAD_MENU';
export const SELECT_MENU_ITEM = 'SELECT_MENU_ITEM';

// Cart
export const LOAD_CART_INFO = 'LOAD_CART_INFO';
export const SAVE_CART_INFO = 'SAVE_CART_INFO';
export const LOAD_CART_ITEMS = 'LOAD_CART_ITEMS';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const ADD_CART_ITEM_SUCCESS = 'ADD_CART_ITEM_SUCCESS';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const REMOVE_ALL_CART_ITEMS = 'REMOVE_ALL_CART_ITEMS';
export const REMOVE_CART_ITEM_SUCCESS = 'REMOVE_CART_ITEM_SUCCESS';

// Checkout
export const CHECKOUT = 'CHECKOUT';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILURE = 'CHECKOUT_SUCCESS';

// Orders
export const LOAD_ORDERS = 'LOAD_ORDERS';
export const LOAD_ORDERS_SUCCESS = 'LOAD_ORDERS_SUCCESS';
export const SELECT_ORDER = 'SELECT_ORDER';

// Order Details
export const LOAD_ORDER_DETAILS = 'LOAD_ORDER_DETAILS';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';
export const CANCEL_ORDER_FAILURE = 'CANCEL_ORDER_FAILURE';

// Profile
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
